---
classes:
  - 'bind9'

bind9::forwarders:
  - '2606:4700:4700::1111'
  - '2606:4700:4700::1001'
  - '1.1.1.1'
  - '1.0.0.1'

bind9::acls:
  - name: 'home-networks'
    subnets:
      - '2001:8b0:7a51::/48'
      - '192.168.64.0/22'
      - '10.0.0.0/24'
  - name: 'vagrant'
    subnets:
      - '10.0.0.0/16'
      - '192.168.99.0/24'

bind9::recursion: true
bind9::zones:
  'onthebeach.co.uk':
    type: 'forward'
    forwarders:
      - '172.23.1.25'
      - '172.23.1.28'
  'otbeach.com':
    type: 'forward'
    forwarders:
      - '172.23.1.25'
      - '172.23.1.28'
  'otb.local':
    type: 'forward'
    forwarders:
      - '172.23.1.25'
      - '172.23.1.28'
  'otbsrv':
    type: 'forward'
    forwarders:
      - '172.23.1.25'
      - '172.23.1.28'
  'mgmt.home.crigby.net':
    type: 'master'
    ttl: 300
    soa:
      email: 'root.mgmt.home.crigby.net.'
      refresh: 86400
      retry: 3600
      expire: 86400
      nttl: 300
    records:
      - name: 'ns1'
        type: 'A'
        value: '192.168.64.16'
      - name: 'ns1'
        type: 'AAAA'
        value: '2001:8b0:7a51:2f67::16'
      - name: '@'
        type: 'NS'
        value: 'ns1'
      - name: 'gf-core-sw1'
        type: 'A'
        value: '192.168.64.2'
      - name: '1f-studio-sw1'
        type: 'AAAA'
        value: '2001:8b0:7a51:2f67::4'
      - name: 'cctv'
        type: 'AAAA'
        value: '2001:8b0:7a51:2f67::13'
      - name: 'cctv'
        type: 'A'
        value: '192.168.64.13'
      - name: 'fileserver'
        type: 'AAAA'
        value: '2001:8b0:7a51:2f67::12'
      - name: 'fileserver'
        type: 'A'
        value: '192.168.64.12'
      - name: 'gf-livingroom-sw1'
        type: 'A'
        value: '192.168.64.3'
      - name: 'gw1'
        type: 'A'
        value: '192.168.64.1'
      - name: 'gw1'
        type: 'AAAA'
        value: '2001:8b0:7a51:2f67::1'
      - name: 'pdu1'
        type: 'A'
        value: '192.168.64.5'
      - name: 'prometheus'
        type: 'AAAA'
        value: '2001:8b0:7a51:2f67::15'
      - name: 'pve1'
        type: 'A'
        value: '192.168.64.11'
      - name: 'unifi'
        type: 'AAAA'
        value: '2001:8b0:7a51:2f67::14'
      - name: 'nora'
        type: 'AAAA'
        value: '2001:8b0:7a51:2f67::2'
      - name: 'kube-1'
        type: 'A'
        value: '192.168.64.50'
      - name: 'kube-2'
        type: 'A'
        value: '192.168.64.51'
      - name: 'kube-3'
        type: 'A'
        value: '192.168.64.52'
      - name: 'kube-4'
        type: 'A'
        value: '192.168.64.53'
      - name: 'kube-1'
        type: 'AAAA'
        value: '2001:8b0:7a51:2f67::50'
      - name: 'kube-2'
        type: 'AAAA'
        value: '2001:8b0:7a51:2f67::51'
      - name: 'kube-3'
        type: 'AAAA'
        value: '2001:8b0:7a51:2f67::52'
      - name: 'kube-4'
        type: 'AAAA'
        value: '2001:8b0:7a51:2f67::53'
      - name: 'download'
        type: 'A'
        value: '192.168.64.17'
      - name: 'download'
        type: 'AAAA'
        value: '2001:8b0:7a51:2f67::17'
      - name: 'pdu2'
        type: 'A'
        value: '192.168.64.120'
  'general.home.crigby.net':
    type: 'master'
    ttl: 300
    soa:
      email: 'root.mgmt.home.crigby.net.'
      refresh: 86400
      retry: 3600
      expire: 86400
      nttl: 300
    records:
      - name: '@'
        type: 'NS'
        value: 'ns1.mgmt.home.crigby.net.'
      - name: 'fileserver'
        type: 'A'
        value: '192.168.65.12'
      - name: 'fileserver'
        type: 'AAAA'
        value: '2001:8b0:7a51:2f66::12'
      - name: 'mfc'
        type: 'AAAA'
        value: '2001:8b0:7a51:2f66::4'
  'home.crigby.net':
    type: 'master'
    ttl: 300
    soa:
      email: 'root.mgmt.home.crigby.net.'
      refresh: 86400
      retry: 3600
      expire: 86400
      nttl: 300
    records:
      - name: '@'
        type: 'NS'
        value: 'ns1'
      - name: 'mgmt.home.crigby.net.'
        type: 'NS'
        value: 'ns1.mgmt'
      - name: 'ns1.mgmt'
        type: 'AAAA'
        value: '2001:8b0:7a51:2f67::16'
      - name: 'ns1'
        type: 'AAAA'
        value: '2001:8b0:7a51:2f67::16'
      - name: 'irc'
        type: 'CNAME'
        value: 'nora.mgmt.home.crigby.net.'
